node ('master'){

    stage ('Checkout master') {
        checkout scm
    }
    
    stage ("Build") {
        sh './SupportFiles/build.sh'
    }

    stage ("Deploy") {
        sh './SupportFiles/deploy.sh'
    }
    
}